### ISSUE TITLE
Itamaeを使ったApacheインストール

### ISSUE THREAD

**Issue by hico-horiuchi** [sai-lab/rookie-training#44]
各自の`Vagrantfile`を編集し、Ansibleによるプロイジョニングを設定する。

```ruby
config.vm.provision :itamae do |itamae|
  itamae.sudo = true
  itamae.recipes = ['apache.rb']
end
```

下記の通り`apache.rb`を作成し、Apacheのインストールとサービスの起動を行う。
その後、適当な文字列を`index.html`に書き込む。

  - `vagrant/s00t000`に`itamae/default.rb`を`apache.rb`としてコピーする。
  - [packageリソース](https://github.com/itamae-kitchen/itamae/wiki/package-resource)を使って`apache2`をインストールする。
  - [serviceリソース](https://github.com/itamae-kitchen/itamae/wiki/service-resource)を使って`apache2`を再起動する。
  - [executeリソース](https://github.com/itamae-kitchen/itamae/wiki/execute-resource)を使って`/var/www/html/index.html`に`echo`コマンドでリダイレクトする。

Vagrantをログアウトし，`curl http://192.168.11.40/`を実行する。
結果が`index.html`にリダイレクトした文字列であるか確認する。

**Comment by nechinechi** [comment]
`curl http://192.168.11.40/`により，`echo`コマンドでリダイレクトした文字を確認することができたのですが，プロビジョニングの際に大量の文字が出力されます．

行った操作は，`vagrant plugin install vagrant-itamae`を実行し，`Vagrantfile`は指定の通り編集し，`apache.rb`は画像のように編集しました．
![apache_image](https://cloud.githubusercontent.com/assets/15319734/12374374/02fbd258-bcdd-11e5-9bd9-5b269b91fe6a.png)


これでVagrantを起動し，プロビジョニングすると，大量の文字が出てきます．`apache.rb`のserviceリソースとexecuteリソースに関する記述の部分をコメントアウトしていても同じようになります．文字数が多いので一部ですが，下の画像がプロビジョニングの結果です．

`curl http://192.168.11.40/`の結果は正しく表示されているのですが，プロビジョニングがこれで正常なのかわからないです．
足りない部分があれば，教えて頂きたいです．

**Comment by nechinechi** [comment]
`curl http://192.168.11.40/`により，`echo`コマンドでリダイレクトした文字を確認することができたのですが，プロビジョニングの際に大量の文字が出力されます．

行った操作は，`vagrant plugin install vagrant-itamae`を実行し，`Vagrantfile`は指定の通り編集し，`apache.rb`は画像のように編集しました．
![apache_image](https://cloud.githubusercontent.com/assets/15319734/12374374/02fbd258-bcdd-11e5-9bd9-5b269b91fe6a.png)


これでVagrantを起動し，プロビジョニングすると，大量の文字が出てきます．`apache.rb`のserviceリソースとexecuteリソースに関する記述の部分をコメントアウトしていても似たようになります．文字数が多いので一部ですが，下の画像がプロビジョニングの結果です．
![provision_result_image](https://cloud.githubusercontent.com/assets/15319734/12374380/201931be-bcdd-11e5-93b3-2fb3df66d311.png)


`curl http://192.168.11.40/`の結果は正しく表示されているのですが，プロビジョニングがこれで正常なのかわからないです．
足りない部分があれば，教えて頂きたいです．

**Comment by nechinechi** [comment]
issueのクローズはミスです．すみません．

**Comment by nechinechi** [comment]
`curl http://192.168.11.40/`により，`echo`コマンドでリダイレクトした文字を確認することができたのですが，プロビジョニングの際に大量の文字が出力されます．

行った操作は，`vagrant plugin install vagrant-itamae`を実行し，`Vagrantfile`は指定の通り編集し，`apache.rb`は画像のように編集しました．
![apache_image](https://cloud.githubusercontent.com/assets/15319734/12374374/02fbd258-bcdd-11e5-9bd9-5b269b91fe6a.png)


これでVagrantを起動し，プロビジョニングすると，大量の文字が出てきます．`apache.rb`のserviceリソースとexecuteリソースに関する記述の部分をコメントアウトしていても似たようになります．文字数が多いので一部ですが，下の画像がプロビジョニングの結果です．
![provision_result_image](https://cloud.githubusercontent.com/assets/15319734/12374380/201931be-bcdd-11e5-93b3-2fb3df66d311.png)


`curl http://192.168.11.40/`の結果は正しく表示されているのですが，プロビジョニングがこれで正常なのかわからないです．
足りない部分があれば，教えて頂きたいです．
